version: '3.3'
services:
    nginx:
        ports:
            - '8080:8080'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        restart: always
        logging:
            options:
                max-size: 100M
        image: ./domhash
